config/routes.rb
Rails.application.routes.draw do
  # Forem Engine
  mount Forem::Engine, :at => '/forums'

  # Root path
  root 'home#index'

  # Devise users
  devise_for :users

  # Admin control panel
  namespace :admin do
    resources :users
    resources :server_families
  end

  resources :servers, only: [:index, :show]

  resources :punishments

  # Information

  get '/info/terms', to: 'home#terms', as: 'terms'
  get '/info/rules', to: 'home#rules', as: 'rules'

  # Users and Stats

  get '/stats', to: 'stats#index', as: 'stats'
  get '/staff', to: 'staff#index', as: 'staff'
  get '/users/:username', to: 'application#profile', as: 'profile'

  # Server shop

  get '/shop', to: 'application#shop', as: 'shop'

  # Support tickets

  resources :reports do
    put :close
    put :open
  end
  get '/support', to: 'reports#index'
end

app/models/server_family.rb
class ServerFamily < ActiveRecord::Base
  class << self
    def by_priority
      order(:priority)
    end
  end
end

app/controllers/admin/server_families_controller.rb
class Admin::ServerFamiliesController < ApplicationController
  before_filter :set_family, :only => [:show, :edit, :destroy, :update]

  def index
    @families = ServerFamily.all.by_priority
  end

  def show
  end

  def edit
  end

  def destroy
    @family.destroy
    flash[:notice] = 'Successfully deleted a server family'
    redirect_to admin_server_families_path
  end

  def create
    @family = ServerFamily.new(family_params)
    if @family.save
      flash[:notice] = 'Successfully created a new server family.'
      redirect_to [:admin, @family]
    else
      flash[:alert] = 'Unable to save this server family.'
      render 'edit'
    end
  end

  def update
    if @family.update_attributes(family_params)
      flash[:notice] = 'Successfully updated server family'
      redirect_to [:admin, @family]
    else
      flash[:alert] = 'Unable to save server changes'
      render :edit
    end
  end

  def new
    @family = ServerFamily.new
  end

  private
  def set_family
    @family = ServerFamily.find(params[:id])
  end

  def family_params
    params.require(:server_family).permit(:gamemode, :priority, :display)
  end
end

app/views/admin/server_families/_form.html.erb
<%= simple_form_for([:admin, @family]) do |f| %>
<%= f.input :gamemode, input_html: { class: 'form-control' } %>
<p class="help-block">The name of the servers in the database.</p>
<%= f.input :display, input_html: { class: 'form-control' } %>
<p class="help-block">The text to display as the name of the family.</p>
<%= f.input :priority, input_html: { class: 'form-control' } %>
<p class="help-block">The order to display the server families.</p>
<%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/admin/server_families/edit.html.erb
<div class='row'>
	<div class='page-header'>
		<%= link_to 'Back', admin_server_families_path, class: 'btn btn-danger pull-right' %>
		<h1>Server Admin Panel<small> Editing Server Family</small></h1>
	</div>
	<div class='col-md-2'>
		<%= render '/forem/admin/base/side' %>
	</div>
	<div class='col-md-10'>
		<%= render 'form' %>
	</div>
</div>

app/views/admin/server_families/index.html.erb
<div class='row'>
	<div class='page-header'>
		<%= link_to 'New Family', new_admin_server_family_path, class: 'btn btn-primary pull-right' %>
		<h1>Server Admin Panel<small> Manage Server Groups</small></h1>
	</div>
	<div class='col-md-2'>
		<%= render '/forem/admin/base/side' %>
	</div>
	<div class='col-md-10'>
		<table class='table table-striped'>
			<thead>
				<tr>
					<th>Family</th>
					<th>Display</th>
					<th>Priority</th>
					<th>Edit</th>
					<th>Delete</th>
				</tr>
			</thead>
			<tbody>
				<% @families.each do |family| %>
				<tr>
					<td><%= link_to family.gamemode, admin_server_family_path(family) %></td>
					<td><%= link_to family.display,admin_server_family_path(family) %></td>
					<td><%= family.priority %></td>
					<td><%= link_to 'Edit', edit_admin_server_family_path(family) %></td>
					<td><%= link_to 'Delete', admin_server_family_path(family), method: :delete, :data => { confirmation: 'Are you sure you want to delete this server group?' } %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/admin/server_families/new.html.erb
<div class='row'>
	<div class='page-header'>
		<%= link_to 'Cancel', admin_server_families_path, class: 'btn btn-danger pull-right' %>
		<h1>Server Admin Panel<small> New Server Family</small></h1>
	</div>
	<div class='col-md-2'>
		<%= render '/forem/admin/base/side' %>
	</div>
	<div class='col-md-10'>
		<%= render 'form' %>
	</div>
</div>

app/views/admin/server_families/show.html.erb
<div class='row'>
	<div class='page-header'>
		<%= link_to 'Delete', admin_server_family_path(@family), method: :delete, :data => { confirmation: 'Are you sure you want to delete this family?' }, class: 'btn btn-danger pull-right' %>
		<h1>Server Admin Panel<small> Server Family</small></h1>
	</div>
	<div class='col-md-2'>
		<%= render '/forem/admin/base/side' %>
	</div>
	<div class='col-md-10'>
		<%= render 'form' %>
	</div>
</div>