config/routes.rb
Rails.application.routes.draw do
  # Forem Engine
  mount Forem::Engine, :at => '/forums'

  # Root path
  root 'home#index'

  # Devise users
  devise_for :users

  # Admin control panel
  namespace :admin do
    resources :users
    resources :server_families
  end

  resources :servers, only: [:index, :show]

  resources :punishments

  # Information

  get '/info/terms', to: 'home#terms', as: 'terms'
  get '/info/rules', to: 'home#rules', as: 'rules'

  # Users and Stats

  get '/stats', to: 'stats#index', as: 'stats'
  get '/staff', to: 'staff#index', as: 'staff'
  get '/users/:username', to: 'application#profile', as: 'profile'

  # Server shop

  get '/shop', to: 'application#shop', as: 'shop'

  # Support tickets

  resources :reports do
    put :close
    put :open
  end
  get '/support', to: 'reports#index'
end

app/models/death.rb
class Death < ActiveRecord::Base
  belongs_to :server_session
  class << self
    def kills_for(uuid)
      where(:killer_uuid => uuid)
    end

    def deaths_for(uuid)
      where(:victim_uuid => uuid)
    end

    def for_gamemode(gamemode)
      where(:gamemode => gamemode)
    end
  end 

  def killer_username
    MinecraftUser.for_uuid(killer_uuid).username
  end

  def victim_username
    MinecraftUser.for_uuid(victim_uuid).username
  end
end

app/models/minecraft_user.rb
class MinecraftUser < ActiveRecord::Base
  class << self
    def for_uuid(uuid)
      where(:uuid => uuid).first
    end

    def for_user(username)
      User.where(:uuid => where(:username => username).first.uuid).first
    end
  end

  def kills
    Death.where(:killer_uuid => self.uuid)
  end

  def deaths
    Death.where(:victim_uuid => self.uuid)
  end
end

app/models/minecraft_username.rb
class MinecraftUsername < ActiveRecord::Base
  class << self
    def for_uuid(uuid)
      where(:uuid => uuid).first
    end

    def for_user(username)
      User.where(:uuid => where(:username => username).first.uuid).first
    end
  end
end

app/models/punishment.rb
class Punishment < ActiveRecord::Base

  def punisher_username
    MinecraftUser.for_uuid(punisher).username
  end

  def punished_username
    MinecraftUser.for_uuid(punished).username
  end

  def get_color
    color = case punishment_type
    when "Warn" then 'green'
    when "Ban" then 'red'
    when "Kick" then 'orange'
    else ''
    end
    return color
  end
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :reporter, class_name: 'User', inverse_of: :reports
end

app/models/server_family.rb
class ServerFamily < ActiveRecord::Base
  class << self
    def by_priority
      order(:priority)
    end
  end
end

app/models/server_session.rb
class ServerSession < ActiveRecord::Base
  has_many :deaths

  def online
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  has_many :reports, class_name: 'Report', inverse_of: :reporter

  before_save :reset_colors

  serialize :username_history

  def username
    return MinecraftUser.where(:uuid => uuid).first.username
  end

  def encounters
    encounters = kills + deaths
    encounters.sort_by(:timestamp).reverse
  end

  def kills
    Death.where(:killer_uuid => self.uuid)
  end

  def deaths
    Death.where(:victim_uuid => self.uuid)
  end

  def forem_name
    username
  end

  def forem_email
    email
  end

  def groups
    forem_groups
  end

  def highest_group
    groups.order(:priority).first
  end

  def get_name_color
    group = highest_group
    return '' if !highest_group
    return blank_or_return color ||= group.color
  end

  def get_badge_color
    group = highest_group
    return '' if !highest_group
    blank_or_return badge_color ||= group.badge_color
  end

  def get_badge_text
    group = highest_group
    return '' if !highest_group
    blank_or_return badge_text ||= group.badge_text
  end

  def blank_or_return(field)
    return field.blank? ? nil : field
  end

  def reset_colors
    if badge_text.blank?
      badge_text = nil
    end
    if badge_color.blank?
      badge_color = nil
    end
    if color.blank?
      color = nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    category = Forem::Category.first
    if category
      forum = category.forums.first
      if forum
        return @announcements = forum.topics.limit(3)
      end
    end
    return []
  end

  def terms
  end

  def rules
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_report, only: [:show, :edit, :close]

  def show
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    @report.closed = false
    @report.reporter = current_user
    if @report.save
      redirect_to report_path(@report)
    else
      render :edit
    end
  end

  def edit
  end

  def index
    @reports = Report.all
    case params[:sort]
    when "all"
      @reports = @reports
    when "open"
      @reports = @reports.where(:closed => false)
    when "closed"
      @reports = @reports.where(:open => false)
    else
      @reports = @reports.where(:closed => false)
    end
  end

  def close
    @report.closed = true
    @report.save
    redirect_to report_path(@report), :notice => "Successfully closed a ticket."
  end

  def open
    @report.closed = false
    @report.save
    redirect_to report_path(@report), :notice => "Successfully reopened a ticket."  
  end

  private
  def set_report
    @report = Report.find(params[:id] || params[:report_id])
  end

  def report_params
    params.require(:report).permit(:reason, :reporter_id, :evidence, :closed)
  end
end

app/controllers/staff_controller.rb
class StaffController < ApplicationController
  def index
    @groups = Forem::Group.where(:show_on_staff_page => true)
  end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
    @users = MinecraftUser.all.page(params[:page]).per(20)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def profile_link(user)
    username = user
    is_user = user.class.name == 'User'
    if is_user
      username = user.username
    else
      user_class = MinecraftUser.for_user(user)
      if user_class
        user = user_class
        is_user = true
      end
    end
    link_to username, main_app.profile_path(username), class: 'profile-link', style: "color: #{is_user ? user.get_name_color : ''}"
  end

  def user_badge(user)
    return if user.class.name != 'User'
    group = user.highest_group
    return nil if !group
    content_tag(:span, user.get_badge_text, class: 'badge', style: "color: #{user.get_name_color}; background-color: #{user.get_badge_color}")
  end

  def latest_post(topic)
    post = relevant_posts(topic).last
    text = "#{time_ago_in_words(post.created_at)} #{t("ago")}"
    link_to text, forem.forum_topic_path(post.topic.forum, post.topic, :anchor => "post-#{post.id}", pagination_param => topic.last_page)
  end

  def active(tab, options = {})
    active = false
    options[:controller] ||= params[:controller]
    options[:forums] ||= false
    options[:action] ||= nil
    if options[:forums] && options[:controller].start_with?('forem')
      active = true
    elsif 
      active = tab == options[:controller]
      if options[:action]
        active = params[:action] == options[:action]
      end
    end
    return active ? 'active' : ''
  end

  def timestamp(time)
    time ? time.strftime("%l:%M %p %B %d, %Y") : ''
  end
end

app/helpers/avatar_helper.rb
module AvatarHelper
  def avatar(user, options={})
    image = crafatar_url(user, options)
    options = { :profile => true }.merge(options)
    if options[:profile] == false
      image_tag(image, :alt => "Avatar", class: 'avatar')
    else
      link_to image_tag(image, :alt => "Avatar", class: 'avatar'), main_app.profile_path(user.username)
    end
  end

  def crafatar_url(user, options = {})
    options[:size] ||= 60
    "https://crafatar.com/avatars/#{user.uuid}?size=#{options[:size]}&helm"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/punishments_helper.rb
module PunishmentsHelper
  def expires(punishment)
    if punishment.expires_at
      time_ago_in_words(punishment.expires_at) + ' ago'
    else
      'Never'
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/helpers/staff_helper.rb
module StaffHelper
end

app/helpers/stats_helper.rb
module StatsHelper
  def kd_for(kills, deaths)
    if deaths == 0
      return 'N/A'
    else
      return kills / deaths
    end
  end
end

app/views/forem/admin/forums/_form.html.erb
<%= simple_form_for [forem, :admin, @forum] do |f| %>
  <%= f.association :category, :include_blank => false, input_html: { class: 'form-control' } %>
  <%= f.input :title, input_html: { class: 'form-control' }  %>
  <%= f.input :position, input_html: { class: 'form-control' }  %>
  <%= f.input :description, :as => :text, input_html: { class: 'form-control' }  %>

  <h3><%= t('forem.admin.forum.moderator_groups') %></h3>
  <%= f.association :moderators, :as => :check_boxes %>
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/forem/admin/forums/edit.html.erb
<div class='row'>
	<div class='page-header'>
		<h1>Admin Panel <small><%= t("forem.forum.edit", :title => forem_emojify(@forum.title)).html_safe %></small></h1>
	</div>
	<div class='col-md-2'>
		<%= render '/forem/admin/base/side' %>
	</div>
	<div class='col-md-10'>
		<%= render "form" %>
	</div>
</div>

app/views/forem/admin/forums/index.html.erb
<div class='row'>
  <div class='page-header'>
    <%= link_to t("forem.admin.forum.new_link"), forem.new_admin_forum_path, :class => "btn btn-primary pull-right" %>
    <h1>Admin Panel <small><%= t("forem.admin.forum.index") %></small></h1>
  </div>

  <div class='col-md-2'>
    <%= render '/forem/admin/base/side' %>
  </div>
  <div class='col-md-10'>
    <% @forums.group_by(&:category).each do |category, forums| %>
    <h2><%= category.try(:name) || t('.no_category') %></h2>

    <table id='forums' class='forums table table-striped' cellspacing='0'>
      <thead>
        <tr>
          <th><%= t('forum', :scope => 'forem.general') %></th>
          <th><%= t('edit', :scope => 'forem.admin.forums') %></th>
          <th><%= t('delete', :scope => 'forem.admin.forums') %></th>
          <th><%= t('topics', :scope => 'forem.general') %></th>
          <th><%= t('posts', :scope => 'forem.general') %></th>
        </tr>
      </thead>
      <tbody>
        <% forums.each do |forum| %>
        <tr class="forum <%= cycle("odd", "even") %>">
          <td>
            <%= link_to forem_emojify(forum.title), forem.forum_path(forum) %>
            <div class='description'><%= forem_format(forum.description) %></div>
            <%= t('.last_post') %>
            <% if last_post = forum.posts.last %>
            <%= link_to(forem_emojify(last_post.topic.subject), forem.forum_topic_path(forum, last_post.topic)) -%> <%= t('by') %> <%= profile_link(last_post.user) %> <%= time_ago_in_words(last_post.created_at) -%>
            <% else %>
            <%= t('.none') %>
            <% end %>
            <br>
            <span class='moderators'>
              <strong><%= t('.moderators') %>:</strong>
              <% if forum.moderators.exists? %>
              <% forum.moderators.map do |moderator| %>
              <%= link_to moderator, [forem, :admin, moderator] %>
              <% end.to_sentence %>
              <% else %>
              <%= t('.none') %>
              <% end %>
            </span>
          </td>
          <td><%= link_to t('edit', :scope => 'forem.admin.forums'), forem.edit_admin_forum_path(forum), :class => "btn btn-info" %></td>
          <td><%= link_to t('delete', :scope => 'forem.admin.forums'), forem.admin_forum_path(forum), :method => :delete, data: { :confirm => t("delete_confirm", :scope => 'forem.admin.forums') }, :class => "btn btn-danger" %></td>
          <td><%= forum.topics.count %></td>
          <td><%= forum.posts.count %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</div>

app/views/forem/admin/forums/new.html.erb
<div class='row'>
	<div class='page-header'>
		<h1>Admin Panel <small><%= t("forem.forum.new") %></small></h1>
	</div>
	<div class='col-md-2'>
		<%= render '/forem/admin/base/side' %>
	</div>
	<div class='col-md-10'>
		<%= render 'form' %>
	</div>
</div>

app/views/forem/admin/topics/_form.html.erb
<%= simple_form_for [forem, :admin, @topic.forum, @topic] do |f| %>
  <%= f.input :subject, input_html: { class: 'form-control' } %>
  <br />
  <%= f.association :forum , :label => "Forum", input_html: { class: 'form-control' } %>
  <br />
  <%= f.label :locked %>
  <%= f.check_box :locked %>
  <br />
  <%= f.label :pinned %>
  <%= f.check_box :pinned %>
  <br />
  <%= f.label :hidden %>
  <%= f.check_box :hidden %>

  <br />
  <%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/forem/admin/topics/edit.html.erb
<div class='row'>
	<div class='page-header'>
		<h1><%= t("forem.topic.edit", :subject => @topic.subject) %></h1>
	</div>
	<div class='col-md-2'>
		<%= render '/forem/admin/base/side' %>
	</div>
	<div class='col-md-10'>
		<%= render "form" %>
	</div>
</div>

app/views/forem/categories/_category.html.erb
<% if can?(:read, category) %>
  <div id='category_<%= category.id %>' class='category'>
    <h2><%= link_to forem_emojify(category.name), [forem, category] %></h2>
    <%= render "/forem/forums/listing", :category => category %>
  </div>
<% end %>

app/views/forem/categories/show.html.erb
<div class='category'>
  <h2><%= link_to t('forem.forum.forums'), forem.forums_path %> &raquo; <%= link_to forem_emojify(@category), [forem, @category] %></h2>
  <%= render @category %>
</div>

app/views/forem/forums/_forum.html.erb
<% if can?(:read, forum) %>
  <tr class="forum <%= cycle("odd", "even") %>">
    <td>
      <%= link_to forem_emojify(forum.title), forem.forum_path(forum), :class => "title" %>
      <div class='description'><%= forem_format(forum.description) %></div>
      <%= t('forem.forums.index.last_post') -%>
      <span class='last_post'>
        <% if last_post = forum.last_post_for(forem_user) -%>
          <%= link_to(forem_emojify(last_post.topic.subject), forem.forum_topic_path(forum, last_post.topic)) -%> <%= t('by') %> <%= last_post.user.forem_name %>
          <time datetime="<%= last_post.created_at.to_s(:db) -%>"><%= "#{time_ago_in_words(last_post.created_at)} #{t("ago")}" %></time>
        <% else %>
          <%= t('forem.forums.index.none') -%>
        <% end %>
      </span>
    </td>
    <td class="topics-count"><%= topics_count(forum) %></td>
    <td class="posts-count"><%= posts_count(forum) %></td>
    <td class="views-count"><%= forum.views_count %></td>
  </tr>
<% end %>

app/views/forem/forums/_head.html.erb
<div class='page-header'>
  <h1>
    <div id='forum_topic_links' class='btn-group pull-right'>
      <% unless @topic.try(:new_record?) %>
      <% if can? :create_topic, @forum %>
      <%= link_to t('forem.topic.links.new'), forem.new_forum_topic_path(forum), :class => "btn btn-primary", :id => "new-topic" %>
      <% end %>
      <% end %>
      <% if can? :moderate, @forum %>
      <%= link_to t('forem.forum.moderator_tools'), forem.forum_moderator_tools_path(forum), :class => "btn btn-primary" %>
      <% end %>
    </div> 
  <%= t('forem.forum.forums') %> 
  <small><%= forum.name %></small>
</h1>
</div>

app/views/forem/forums/_listing.html.erb
<table id='forums' class='forums table table-striped' cellspacing='0'>
  <thead>
  <tr>
    <th class="desc-and-last-post"><%= t('forum', :scope => 'forem.general') %></th>
    <th class="topics-count"><%= t('topics', :scope => 'forem.general') %></th>
    <th class="posts-count"><%= t('posts', :scope => 'forem.general') %></th>
    <th class="views-count"><%= t('forem.forums.index.views') %></th>
  </tr>
  </thead>
  <tbody>
    <%= render category.forums %>
  </tbody>
</table>

app/views/forem/forums/_side.html.erb
<h3><%= t('home') %></h3>
<ul class="nav nav-pills nav-stacked">
	<li role="presentation"><a href=<%= forem.root_path %>><%= t('latest') %></a></li>
</ul>

<% Forem::Category.all.each do |category| %>
<h3><%= category.name %></h3>
<% category.forums.each do |forum| %>
<ul class="nav nav-pills nav-stacked">
	<li role="presentation"><a href=<%= forem.forum_path(forum) %>><%= forem_emojify(forum.title) %></a></li>
</ul>
<% end %>
<% end %>

app/views/forem/forums/index.html.erb
<div class="page-header">
	<h1><strong><i class="fa fa-pencil"></i> <%= t('.title') %></strong><small> <%= t('.community_discussion') %></small></h1>
</div>
<div class="row">
	<div class="col-md-2">
		<%= render '/forem/forums/side' %>
	</div>
	<div class="col-md-10">
		<h1>Latest Discussions</h1>
		<hr>
		<%= render '/forem/topics/topics', topics: Forem::Topic.where(:locked => false).where(:pinned => false).where(:hidden => false) %>
	</div>
</div>
<footer id='admin_link'>
	<% if forem_admin? %>
	<%= link_to t("area", :scope => "forem.admin"), forem.admin_root_path %>
	<% end %>
</footer>

app/views/forem/forums/show.html.erb
<div class="page-header">
  <div class='btn-group pull-right'>
    <% unless @topic.try(:new_record?) %>
    <% if can? :create_topic, @forum %>
    <%= link_to t('forem.topic.links.new'), forem.new_forum_topic_path(@forum), :class => "btn btn-primary", :id => "new-topic" %>
    <% end %>
    <% end %>
  </div>
  <h1><strong><i class="fa fa-pencil"></i> <%= t('.title') %></strong><small> <%= @forum.name %></small></h1>
</div>
<div class="row">
  <div class="col-md-2">
    <%= render '/forem/forums/side' %>
  </div>
  <div class="col-md-10">
    <h1><%= @forum.name %></h1>
    <hr>
    <%= render '/forem/topics/topics', topics: Forem::Topic.where(:locked => false).where(:pinned => false).where(:hidden => false) %>
  </div>
</div>
<footer id='admin_link'>
  <% if forem_admin? %>
  <%= link_to t("area", :scope => "forem.admin"), forem.admin_root_path %>
  <% end %>
</footer>

app/views/forem/posts/_form.html.erb
<%= f.input :text, :input_html => { :class => "form-control", id: 'post-content', rows: 8 } %>

<% if params[:reply_to_id] %>
  <%= f.hidden_field :reply_to_id, :value => params[:reply_to_id] %>
<% end %>

app/views/forem/posts/_moderation_tools.html.erb
<%= fields_for "posts[#{post.id}]" do |f| %>
  <%= render "/forem/moderation/options", :f => f %>
<% end %>
<br>

app/views/forem/posts/_post.html.erb
<div class="row" id="post-<%= post.id.to_s %>">
  <div id='post_<%= post_counter + 1 %>' class='post <%= cycle('odd', 'even') -%> col-md-12'>

    <div class='contents'>
      <div class='user col-md-2'>
        <div class='icon' align='center'><%= avatar(post.user, :size => 100) %></div>
        <div class='username' align='center'>
          <% if post.user.is_a?(Forem::NilUser) %>
          <%= t(:deleted) %>
          <% else %>
          <%= profile_link(post.user) %>
          <%= user_badge(post.user) %>
          <% end %>
        </div>
      </div>

      <div class='contents col-md-10'>
        <% if post.reply_to %>
        <blockquote class='reply-to'>
          <% reply_to = post.reply_to %>
          <div class="collapse" id="quote-<%= post.id %>">
            <p>
              <%= forem_format(reply_to.text) %>
            </p>
          </div>
          <a data-toggle="collapse" data-target="#quote-<%= post.id %>" style='cursor: pointer;'>
            <small><%= t("forem.post.in_reply_to") %> <%= reply_to.user.username %></small>
          </a>
        </blockquote>
        <% end %>
        <%= forem_format(post.text) %>


      </div>
    </div>
  </div>
</div>
<% if forem_user %>
<div class='row-fluid post-ribbon'>
  <div class='col-md-10 col-md-offset-2'>
    <i class='fa fa-calendar-o'></i><%= link_to post_time_tag(post), forem.forum_topic_path(post.topic.forum, post.topic, anchor: 'post-' + post.id.to_s, pagination_param => post.topic.last_page) %>
    <% unless !defined?(hide_ribbon).nil? %>
    <% if can?(:reply, post.topic) %>
    <% if post.topic.can_be_replied_to? %>
    <i class='fa fa-comment-o'></i><%= link_to t('reply', :scope => 'forem.topic'), forem.new_forum_topic_post_path(post.forum, post.topic, :reply_to_id => post.id), :"data-toggle" => 'tooltip', title: 'Reply to this post as a quote' %>
    <% end %>
    <% end %>
    <% if post.owner_or_admin?(forem_user) %>
    <% if can?(:edit_post, post.topic.forum) %>
    <i class='fa fa-pencil'></i><%= link_to t('edit', :scope => 'forem.buttons.post'), forem.edit_forum_topic_post_path(post.forum, post.topic, post), title: 'Edit this post', :"data-toggle" => 'tooltip' %>
    <% end %>
    <% if can?(:destroy_post, post.topic.forum) %>
    <i class='fa fa-trash-o'></i><%= link_to t('delete', :scope => 'forem.topic'), forem.forum_topic_post_path(post.forum, post.topic, post), :method => :delete, data: { :confirm => t("are_you_sure") }, :"data-toggle" => 'tooltip', title: 'Delete this post' %>
    <% end %>
    <% end %>
    <% end %>
  </div>
</div>
<% end %>
<br>
<hr>

app/views/forem/posts/_reply_to_post.html.erb
<div class='row'>
  <div class='col-md-2'>
    <%= render '/forem/forums/side' %>
  </div>
  <div class='col-md-10'>
    <div id='post_<%= post.id %>' class='reply_to_post post <%= cycle('odd', 'even') -%> col-md-10'>
      <div class='contents col-md-7'>
        <time datetime="<%= post.created_at.to_s(:db) -%>"><%= "#{time_ago_in_words(post.created_at)} #{t("ago")}" %></time>
        <%= forem_format(post.text) %>

        <% if post.reply_to %>
        <span class='in_reply_to'>
          <%= link_to "#{t("forem.post.in_reply_to")} #{post.reply_to.user.forem_name}", "#post-#{post.reply_to.id}" %>
        </span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/forem/posts/edit.html.erb
<div class='container'>

	<%= render :partial => 'forem/forums/head', :locals => { :forum => @topic.forum } %>

	<div class='row'>
		<div class='col-md-2'>
			<%= render '/forem/forums/side' %>
		</div>
		<div class='col-md-10'>
			<div role="tabpanel">

				<ul class="nav nav-tabs" role="tablist">
					<li role="presentation" class="active"><a href="#reply" aria-controls="reply" role="tab" data-toggle="tab">Edit</a></li>
					<% if params[:reply_to_id] %>
					<li role="presentation"><a href="#original" aria-controls="original" role="tab" data-toggle="tab">Original Content</a></li>
					<% end %>
				</ul>

				<div class="tab-content">
					<div role="tabpanel" class="tab-pane active" id="reply">
						<%= simple_form_for [forem, @topic.forum, @topic, @post] do |f| %>
						<p>
							<%= render :partial => "form", :locals => { :f => f } %>
						</p>
						<p>
							<%= f.submit t("forem.post.buttons.save"), :class => "btn btn-primary" %>
						</p>
						<% end %>
					</div>
					<% if params[:reply_to_id] %>
					<div role="tabpanel" class="tab-pane" id="original">
						<div class='original-post' style='padding-top: 20px;'>
							<%= render :partial => "forem/posts/post", locals: { :post => Forem::Post.find(params[:reply_to_id]), post_counter: 1, hide_ribbon: true } %>
						</div>
					</div>
					<% end %>
				</div>

			</div>
		</div>
	</div>
</div>

app/views/forem/posts/new.html.erb
<%= render :partial => 'forem/forums/head', :locals => { :forum => @topic.forum } %>

<div class='row'>
	<div class='col-md-2'>
		<%= render '/forem/forums/side' %>
	</div>
	<div class='col-md-10'>
		<div role="tabpanel">

			<ul class="nav nav-tabs" role="tablist">
				<li role="presentation" class="active"><a href="#reply" aria-controls="reply" role="tab" data-toggle="tab">Reply</a></li>
				<% if params[:reply_to_id] %>
				<li role="presentation"><a href="#original" aria-controls="original" role="tab" data-toggle="tab">Original Content</a></li>
				<% end %>
			</ul>

			<div class="tab-content">
				<div role="tabpanel" class="tab-pane active" id="reply">
					<%= simple_form_for [forem, @topic.forum, @topic, @post] do |f| %>
					<p>
						<%= render :partial => "form", :locals => { :f => f } %>
					</p>
					<p>
						<%= f.submit t("forem.post.buttons.reply"), :class => "btn btn-primary" %>
					</p>
					<% end %>
				</div>
				<% if params[:reply_to_id] %>
				<div role="tabpanel" class="tab-pane" id="original">
					<div class='original-post' style='padding-top: 20px;'>
						<%= render :partial => "forem/posts/post", locals: { :post => Forem::Post.find(params[:reply_to_id]), post_counter: 1, hide_ribbon: true } %>
					</div>
				</div>
				<% end %>
			</div>

		</div>
	</div>
</div>

app/views/forem/topics/_form.html.erb
<%= simple_form_for [forem, @forum, @topic] do |f| %>
<br />
<%= f.input :subject %>
<br />
<%= f.simple_fields_for :posts do |post| %>
<%= render :partial => "forem/posts/form", :locals => { :f => post }%>
<% end %>
<br />
<%= f.submit :class => "btn btn-primary" %>
<% end %>

app/views/shared/_home.html.erb
<div id="home-carousel" class="carousel slide" data-ride="carousel">
  <div class="container">
    <div class="carousel-caption">
      <h1 style='font-size: 100px;'><strong><u>PurePvP</u></strong></h1>
      <h1>The PvP Network</h1>
      <p style="padding-top: 30px">
        <a class="btn btn-lg btn-primary" href="<%= servers_path %>">Play &raquo;</a>
        <a class="btn btn-lg btn-primary" href="<%= new_user_registration_path %>">Register &raquo;</a>
      </p>
    </div>
  </div>
  <ol class="carousel-indicators">
    <li data-target="#home-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#home-carousel" data-slide-to="1"></li>
  </ol>

  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag 'carousel_one.png', alt: 'Home Image #1' %>
    </div>
    <div class="item">
      <%= image_tag 'carousel_two.png', alt: 'Home Image #2' %>
    </div>
  </div>
</div>
<div class="navbar navbar-default" style="min-height: 30px;">
  <div class="container" style="margin-top: 4px; text-align: center; white-space: nowrap; overflow: hidden; text-overflow : ellipsis">
    <strong>News</strong>:
    <% @announcements.each_with_index do |ann, index| %>
    <%= link_to ann.subject, forem.forum_topic_path(ann.forum, ann) %>
    <% unless index == @announcements.size - 1%>
      <strong> | </strong>
    <% end %>
    <% end %>
  </div>
</div>