config/routes.rb
Rails.application.routes.draw do
  # Forem Engine
  mount Forem::Engine, :at => '/forums'

  # Root path
  root 'home#index'

  # Devise users
  devise_for :users

  # Admin control panel
  namespace :admin do
    resources :users
    resources :server_families
  end

  resources :servers, only: [:index, :show]

  resources :punishments

  # Information

  get '/info/terms', to: 'home#terms', as: 'terms'
  get '/info/rules', to: 'home#rules', as: 'rules'

  # Users and Stats

  get '/stats', to: 'stats#index', as: 'stats'
  get '/staff', to: 'staff#index', as: 'staff'
  get '/users/:username', to: 'application#profile', as: 'profile'

  # Server shop

  get '/shop', to: 'application#shop', as: 'shop'

  # Support tickets

  resources :reports do
    put :close
    put :open
  end
  get '/support', to: 'reports#index'
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :reporter, class_name: 'User', inverse_of: :reports
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_report, only: [:show, :edit, :close]

  def show
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    @report.closed = false
    @report.reporter = current_user
    if @report.save
      redirect_to report_path(@report)
    else
      render :edit
    end
  end

  def edit
  end

  def index
    @reports = Report.all
    case params[:sort]
    when "all"
      @reports = @reports
    when "open"
      @reports = @reports.where(:closed => false)
    when "closed"
      @reports = @reports.where(:open => false)
    else
      @reports = @reports.where(:closed => false)
    end
  end

  def close
    @report.closed = true
    @report.save
    redirect_to report_path(@report), :notice => "Successfully closed a ticket."
  end

  def open
    @report.closed = false
    @report.save
    redirect_to report_path(@report), :notice => "Successfully reopened a ticket."  
  end

  private
  def set_report
    @report = Report.find(params[:id] || params[:report_id])
  end

  def report_params
    params.require(:report).permit(:reason, :reporter_id, :evidence, :closed)
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for @report do |f| %>
<p>
	<%= f.label :reason %>
	<%= f.text_area :reason, class: 'form-control' %>
</p>
<p>
	<%= f.label :evidence, 'Additional Evidence/Information' %>
	<%= f.text_area :evidence, class: 'form-control' %>
</p>
<p>
	<%= f.submit 'Submit', class: 'btn btn-primary' %>
</p>
<% end %>

app/views/reports/index.html.erb
<div class='row'>
	<div class='page-header'>
		<div class="btn-group pull-right">
			<%= link_to 'New Ticket', new_report_path, class: 'btn btn-primary' %>
			<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
				Sort <span class="caret"></span>
			</button>
			<ul class="dropdown-menu" role="menu">
				<li><%= link_to 'All', reports_path(sort: 'all') %></li>
				<li><%= link_to 'Closed', reports_path(sort: 'closed') %></li>
				<li><%= link_to 'Open', reports_path(sort: 'open') %></li>
			</ul>
		</div>
		<h1><i class='fa fa-flag'></i> Support Tickets</h1>
	</div>
	<% if @reports.any? %>
	<table class='table table-striped'>
		<thead>
			<th>ID</th>
			<th>Status</th>
			<th>Reporter</th>
			<th>Reported</th>
			<th>Last Updated</th>
			<th></th>
		</thead>
		<tbody>
			<% @reports.each do |report| %>
			<tr>
				<td><%= link_to report.id, report_path(report) %></td>
				<td><%= report.closed ? 'Closed' : 'Open' %></td>
				<td><%= profile_link(report.reporter) %></td>
				<td><%= time_ago_in_words(report.created_at) + ' ago' %></td>
				<td><%= time_ago_in_words(report.updated_at) + ' ago' %></td>
				<td><%= link_to 'View', report_path(report) %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<% else %>
	<div class='none text-muted' align='center'>No reports found.</div>
	<% end %>
</div>

app/views/reports/new.html.erb
<div class='row'>
	<div class='page-header'>
		<%= link_to 'Cancel', reports_path, class: 'btn btn-danger pull-right' %>
		<h1><i class='fa fa-pencil'></i> New Ticket</h1>
	</div>
	<div class='col-md-6'>
		<%= render 'form' %>
	</div>
	<div class="col-md-6">
		<div class="sidepanel sidepanel-primary">
			<h3><strong><i class="fa fa-lightbulb-o"></i> False Tickets</strong></h3>
			<p><b>Be warned!</b> Abusing the ticket system may result in consequences for wasting staff time, and causing unnecessary confusion. Please be considerate of the time that goes into completing tickets, and do not abuse the system. Thank you.</p>
		</div>
		<div class="sidepanel sidepanel-primary">
			<h3><strong><i class="fa fa-clock-o"></i> Response Times</strong></h3>
			<p><b>Please wait!</b> The Pure PvP staff work as efficiently as possible to complete your ticket as soon as possible, but it may take up to 48 hours for your ticket to be completed. Please wait up to that long before contacting support.</p>
		</div>
	</div>
</div>

app/views/reports/show.html.erb
<div class='row'>
	<div class='page-header'>
		<% if !@report.closed %>
		<%= link_to 'Close', report_close_path(@report), method: :put, class: 'btn btn-primary pull-right' %>
		<% else %>
		<%= link_to 'Reopen', report_open_path(@report), method: :put, class: 'btn btn-primary pull-right' %>
		<% end %>
		<h1>Reports <small>Report #<%= @report.id %></small></h1>
	</div>
	<p>
		<label>Reason:</label>
		<blockquote>
			<%= @report.reason %>
		</blockquote>
	</p>
	<p>
		<label>Evidence/Additional Information:</label>
		<blockquote>
			<%= @report.evidence %>
		</blockquote>
	</p>
</div>